name: PurpurSpy
version: '${project.version}'
main: me.xann.purpurspy.PurpurSpy
api-version: 1.15
authors: [ Xann97 ]
description: Plugin for spying on players.

commands:
  purpurspy:
    description: Plugins main command.
    usage: /<command>

permissions:
  purpurspy.reload:
    description: Allows you to reload the plugin.
    default: op
  purpurspy.sign:
    description: Allows you to spy signs.
    default: op
  purpurspy.book:
    description: Allows you to spy books.
    default: op
  purpurspy.anvil:
    description: Allows you to spy anvils.
    default: op